# Generated by Django 3.0.7 on 2020-06-17 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionTrack', '0002_auto_20200617_1246'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
