# Generated by Django 3.0.7 on 2020-06-23 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionTrack', '0003_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='carbs',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='date',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='fat',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='kcals',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='prot',
        ),
    ]
