# Generated by Django 3.0.7 on 2020-06-23 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionTrack', '0004_auto_20200623_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredients',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dish',
            name='refIngredient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='nutritionTrack.Ingredient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dish',
            name='totalAmount',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
