# Generated by Django 3.0.7 on 2020-06-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionTrack', '0006_auto_20200623_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='fats',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='prots',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
