# Generated by Django 3.0.7 on 2020-06-24 05:30

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionTrack', '0007_auto_20200623_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='ingredients',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
