# Generated by Django 3.0.7 on 2020-06-24 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionTrack', '0008_auto_20200624_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='refIngredient',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nutritionTrack.Ingredient'),
        ),
    ]
