# Generated by Django 3.0.7 on 2020-06-25 03:40

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionTrack', '0010_auto_20200624_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='ration',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
