# Generated by Django 3.0.7 on 2020-06-25 07:29

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionTrack', '0011_date_ration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='ration',
            field=jsonfield.fields.JSONField(default={'food_items': []}),
        ),
    ]
